/*------------------------------------------------------------------------------
Copyright 2021 Garmin Ltd. or its subsidiaries.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
------------------------------------------------------------------------------*/

/**
    @file
    Text handles used in ACDB.

    Copyright 2019-2020 by Garmin Ltd. or its subsidiaries.
*/

#ifndef ACDB_TextHandle_hpp
#define ACDB_TextHandle_hpp

#include "ACDB_pub_types.h"

namespace Acdb {
// These values must always match the text handles in the ActiveCaptain Community API v2.
enum class TextHandle : ACDB_text_handle_type {
  YesValue = 0,
  NoValue = 1,
  UnknownValue = 2,
  NearbyValue = 3,
  PerFootValue = 4,
  PerMeterValue = 5,
  FlatRateValue = 6,
  DateLastModifiedLabel = 7,
  AnchorageValue = 8,
  HazardValue = 9,
  MarinaValue = 10,
  // LocalKnowledgeValue = 11,  -> old type, not used anymore
  // NavigationalValue = 12,    -> old type, not used anymore
  BoatRampValue = 13,
  BusinessValue = 14,
  InletValue = 15,
  BridgeValue = 16,
  LockValue = 17,
  DamValue = 18,
  FerryValue = 19,
  AirportValue = 20,
  SummaryTitle = 21,
  AddressTitle = 22,
  ContactTitle = 23,
  PhoneNumberLabel = 24,
  VhfChannelLabel = 25,
  EmailLabel = 26,
  AfterHourContactLabel = 27,
  AmenitiesTitle = 28,
  AmenitiesNotesLabel = 29,
  BarLabel = 30,
  BoatRampLabel = 31,
  CellReceptionLabel = 32,
  CourtesyCarLabel = 33,
  LaundryLabel = 34,
  LodgingLabel = 35,
  PetsLabel = 36,
  RestaurantLabel = 37,
  RestroomLabel = 38,
  ShowerLabel = 39,
  TransportationLabel = 40,
  TrashLabel = 41,
  WaterLabel = 42,
  WifiLabel = 43,
  BusinessTitle = 44,
  PublicLabel = 45,
  OperatingSeasonLabel = 46,
  SeasonalValue = 47,
  YearRoundValue = 48,
  PaymentLabel = 49,
  CashValue = 50,
  CheckValue = 51,
  CreditValue = 52,
  NavigationTitle = 53,
  DepthLabel = 54,
  TideLabel = 55,
  CurrentLabel = 56,
  StrongValue = 57,
  ModerateValue = 58,
  WeakValue = 59,
  BridgeTypeLabel = 60,
  FixedBridgeValue = 61,
  MoveableBridgeValue = 62,
  BridgeClosedHeightLabel = 63,
  RestrictionNotesLabel = 64,
  NavigationNotesLabel = 65,
  FuelTitle = 66,
  GasLabel = 67,
  EthanolFreeLabel = 68,
  DieselLabel = 69,
  PropaneLabel = 70,
  FuelDepthLabel = 71,
  FuelNotesLabel = 72,
  PerGallonValue = 73,
  DockageTitle = 74,
  DockageNotesLabel = 75,
  HasDocksLabel = 76,
  FreeValue = 77,
  AveragePricePerDayLabel = 78,
  TotalLabel = 79,
  TransientLabel = 80,
  DockTypeLabel = 81,
  WoodDockValue = 82,
  ConcreteDockValue = 83,
  FloatingDockValue = 84,
  FixedDockValue = 85,
  TAlongsideDockValue = 86,
  WharfQuayDockValue = 87,
  OtherDockValue = 88,
  LoaMaxLabel = 89,
  BeamMaxLabel = 90,
  PhoneLabel = 91,
  CableTvLabel = 92,
  LiveaboardLabel = 93,
  DisabilityAccessLabel = 94,
  SecureAccessLabel = 95,
  SecurityPatrolLabel = 96,
  ShorePowerLabel = 97,
  AcPower16Value = 98,
  AcPower30Value = 99,
  AcPower32Value = 100,
  AcPower50Value = 101,
  AcPower64Value = 102,
  AcPower100Value = 103,
  AcPower200Value = 104,
  MooringsTitle = 105,
  MooringNotesLabel = 106,
  DinghyLabel = 107,
  LaunchLabel = 108,
  HasMooringsLabel = 109,
  RetailTitle = 110,
  RetailNotesLabel = 111,
  FishingSuppliesLabel = 112,
  GroceryLabel = 113,
  HardwareLabel = 114,
  IceLabel = 115,
  MarineRetailLabel = 116,
  ServicesTitle = 117,
  ServicesNotesLabel = 118,
  BoatBrokersLabel = 119,
  BottomPaintingLabel = 120,
  CanvasAndUpholsteryLabel = 121,
  CarpentryLabel = 122,
  CharterLabel = 123,
  ElectronicsLabel = 124,
  FiberglassLabel = 125,
  HaulOutLabel = 126,
  MarineHvacLabel = 127,
  MechanicalLabel = 128,
  PaintLabel = 129,
  PlumbingLabel = 130,
  PropellerRepairLabel = 131,
  PumpOutLabel = 132,
  RepairLabel = 133,
  RepairDieselEnginesLabel = 134,
  RepairGasEnginesLabel = 135,
  RescueAndSalvageLabel = 136,
  SailsAndRiggingLabel = 137,
  StorageLabel = 138,
  SurveyorsLabel = 139,
  TowingLabel = 140,
  WashAndWaxLabel = 141,
  WaterTaxiLabel = 142,
  WeldingLabel = 143,
  ReviewsTitle = 144,
  FeaturedReviewTitle = 145,
  FeetUnit = 146,
  MetersUnit = 147,
  NorthAbbr = 148,
  SouthAbbr = 149,
  EastAbbr = 150,
  WestAbbr = 151,
  PerLiterValue = 152,
  SeeAll = 153,
  WriteReview = 154,
  CommentsTitle = 155,
  WriteComment = 156,
  EditReview = 157,
  EditComment = 158,
  PromotionsLabel = 159,
  AdsTitle = 160,
  AdLabel = 161,
  ReportLabel = 162,
  PrevLabel = 163,
  NextLabel = 164,
  SeeAllPhotos = 165,
  PhotosTitle = 166,
  ResponseLabel = 167,
  ElectricLabel = 168,
  MooringDepthLabel = 169,
  DockageDepthLabel = 170,
  MonthJan = 171,
  MonthFeb = 172,
  MonthMar = 173,
  MonthApr = 174,
  MonthMay = 175,
  MonthJun = 176,
  MonthJul = 177,
  MonthAug = 178,
  MonthSep = 179,
  MonthOct = 180,
  MonthNov = 181,
  MonthDec = 182,

  TextHandleCount  // MUST BE LAST
};                 // end of class TextHandle
}  // end of namespace Acdb

#endif  // end of ACDB_TextHandle_hpp
